### ISSUE TITLE
consider using pngjs2

### ISSUE THREAD

**Issue by lukeapage** [yahoo/pngjs-image#10]
I see you are using pngjs for reading and writing png's. That project has been dead a couple of years and I've been working on a replacement - pngjs2, including the bugfixes, which is fully tested and supports multiple bit depths and interlace.

**Comment by marcelerz** [comment]
I already implemented a PNG encoder/decoder from scratch (see ```lib/png``` folder) since ```pngjs``` was limiting the possibilities. I am happy that there is some movement with the project now, but I pretty much moved off of it.
