### ISSUE TITLE
Should be a way to get base64 image

### ISSUE THREAD

**Issue by Daxito** [yahoo/pngjs-image#11]
Should be a way to get image as base64.

**Comment by marcelerz** [comment]
You can do the following to get the base64 image:
```js
var base64Image = 'data:image/png;base64,' + image.getBlob().toString('base64');
```

**Comment by Daxito** [comment]
I will try that, thank you!

**Comment by zyzof** [comment]
Thanks @marcelerz.

I found that to get a base64 image that could be embedded in an HTML `<img>` tag, I had to use:
`var base64Image = 'data:image/png;base64,' + image.toBlobSync().toString('base64');`
