### ISSUE TITLE
[load png from URL]

### ISSUE THREAD

**Issue by gkathan** [yahoo/pngjs-image#8]
hi,
maybe I miss something out - but it looks like that loading a PNG from a http URL instead of local filesystem does not work ... any hints on that ?

**Comment by marcelerz** [comment]
Yes, this was not available. I just added this feature to the readImage static method on the PNGImage object in version v0.11.4. I also added an example to the README. Give it a try and let me know if this is what you were looking for!

**Comment by gkathan** [comment]
yeah mate :-) you made my day - works like a breeze ! greetings from vienna
